[build]
  command = "mkdir -p dist && cp -r index.html src templates dist/"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/templates/*"
  to = "/templates/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200